export * from "./findElementIndexForPoint"
export * from "./getTotalLength"
export * from "./getControlPointsFromPath"
export * from "./calculateTValueForPoint"
export * from "./calculateDistanceAlongPath"
